# Generated by Django 4.1.2 on 2024-07-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_navbar_url_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url_nav',
            field=models.CharField(max_length=100),
        ),
    ]
