# Generated by Django 4.1.2 on 2024-07-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_navbar_url_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(db_column='idAutor', primary_key=True, serialize=False)),
                ('nom_autor', models.CharField(max_length=50)),
                ('nacionalidad_autor', models.CharField(max_length=100)),
            ],
        ),
    ]
