# Generated by Django 4.1.2 on 2024-07-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_autores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=50)),
                ('desc_categoria', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id_libro', models.AutoField(db_column='idLibro', primary_key=True, serialize=False)),
                ('titulo_libro', models.CharField(max_length=50)),
                ('anio_publicacion', models.CharField(max_length=5)),
                ('desc_libro', models.TextField(max_length=500)),
            ],
        ),
    ]
